/**
 * Gemini API integration helper for CREST Capital Management CRM.
 * Requires GEMINI_API_KEY in environment.
 */

export type ChatMessageForSummary = {
  direction: string;
  message_text: string | null;
  sent_at: string | null;
  created_at: string;
};

interface GeminiPart {
  text?: string;
}

interface GeminiCandidate {
  content?: {
    parts?: GeminiPart[];
    role?: string;
  };
  finishReason?: string;
}

interface GeminiApiResponse {
  candidates?: GeminiCandidate[];
  error?: {
    code?: number;
    message?: string;
    status?: string;
  };
}

/**
 * Generates an AI summary of a contact's WhatsApp conversation history using Gemini 3.6 Flash.
 * Produces a concise, scannable summary in at most 2 short sentences (under 40 words total)
 * with an optional next step.
 */
export async function generateChatSummary(
  messages: ChatMessageForSummary[]
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error("GEMINI_API_KEY is not configured.");
  }

  if (!messages || messages.length === 0) {
    throw new Error("No messages provided to summarize.");
  }

  // Format messages chronologically with inbound/outbound labels
  const sorted = [...messages].sort((a, b) => {
    const timeA = new Date(a.sent_at || a.created_at).getTime();
    const timeB = new Date(b.sent_at || b.created_at).getTime();
    return timeA - timeB;
  });

  const formattedHistory = sorted
    .map((m) => {
      const isInbound =
        m.direction === "in" || m.direction?.toLowerCase() === "inbound";
      const label = isInbound ? "Contact (Inbound)" : "Team (Outbound)";
      const timestamp = m.sent_at || m.created_at;
      const text =
        m.message_text && m.message_text.trim()
          ? m.message_text.trim()
          : "[Media / non-text message]";
      return `[${timestamp}] ${label}: ${text}`;
    })
    .join("\n");

  const prompt = `You are an AI assistant for CREST Capital Management's investor CRM.
Summarize this WhatsApp conversation in at most 2 short sentences (under 40 words total). Be direct and specific — no filler phrases like "the contact" or "the team". If there's a clear next step or pending action, end with a separate short line starting with "Next: ".

WhatsApp Conversation History:
${formattedHistory}

Summary:`;

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.6-flash:generateContent?key=${encodeURIComponent(apiKey)}`;

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": apiKey,
    },
    body: JSON.stringify({
      contents: [
        {
          parts: [
            {
              text: prompt,
            },
          ],
        },
      ],
    }),
  });

  const data: GeminiApiResponse = await response.json();

  if (!response.ok || data.error) {
    const errMsg =
      data.error?.message ||
      `Gemini API responded with HTTP status ${response.status}`;
    throw new Error(errMsg);
  }

  const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!generatedText || !generatedText.trim()) {
    throw new Error("No summary generated by Gemini.");
  }

  return generatedText.trim();
}
